# Generated by Django 4.0.1 on 2022-05-30 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanoblog', '0002_alter_author_options_comment_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='shortbio',
            field=models.TextField(max_length=2000),
        ),
    ]
