# Generated by Django 4.0.1 on 2022-06-02 18:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nanoblog', '0003_alter_author_shortbio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='Blogger',
        ),
        migrations.RenameModel(
            old_name='BlogEntry',
            new_name='BlogPost',
        ),
    ]
