# Generated by Django 4.0.1 on 2022-06-02 19:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanoblog', '0004_rename_author_blogger_rename_blogentry_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='date',
            field=models.DateField(default=datetime.datetime.now, editable=False),
        ),
    ]
