# Generated by Django 4.0.1 on 2022-06-03 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nanoblog', '0005_blogpost_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='author',
            new_name='blogger',
        ),
    ]
