# Generated by Django 4.0.1 on 2022-06-10 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nanoblog', '0006_rename_author_blogpost_blogger'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='blogentry',
            new_name='blogpost',
        ),
    ]
