# Generated by Django 4.0.1 on 2022-06-11 07:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanoblog', '0007_rename_blogentry_comment_blogpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='date',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='time',
            field=models.DateField(default=datetime.datetime.now, editable=False),
        ),
    ]
