# Generated by Django 4.0.1 on 2022-06-11 07:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanoblog', '0008_remove_blogpost_date_blogpost_time_comment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
    ]
